[package]
name = "rust-sha512"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha3 = "0.10.0"
rayon = "1.9.0"
crossbeam = "0.8.4"
hex = "0.4.3"